#define DBG_PREFIX "(dzn_gear) "
#define DBG_FUNC_PREFIX __FILE_SHORT__
#define DBG_ diag_log format [DBG_PREFIX + "[" + DBG_FUNC_PREFIX + "] " +
#define EOL ]


#define L(X) toLowerANSI(X)


#define ARR_CAT_EQUIPMENT "EQUIPMENT"
#define ARR_CAT_PRIMARY "PRIMARY WEAPON"
#define ARR_CAT_LAUNCHER "LAUNCHER WEAPON"
#define ARR_CAT_HANDGUN "HANDGUN WEAPON"
#define ARR_CAT_UNIFORM_ITEMS "UNIFORM ITEMS"
#define ARR_CAT_VEST_ITEMS "VEST ITEMS"
#define ARR_CAT_BACKPACK_ITEMS "BACKPACK ITEMS"
#define ARR_CAT_ASSIGNED "ASSIGNED ITEMS"
#define ARR_CAT_INDENTITY "IDENTITY"
#define ARR_CAT_SCRIPT "SCRIPT"
#define ARR_CAT_UNIFORM_TEXTURES "UNIFORM TEXTURES"
#define ARR_CAT_TAGS "TAGS"


#define MAP_CAT_UNIFORM "uniform"
#define MAP_CAT_VEST "vest"
#define MAP_CAT_BACKPACK "backpack"
#define MAP_CAT_HEADGEAR "headgear"
#define MAP_CAT_FACEWEAR "facewear"
#define MAP_CAT_PRIMARY L(ARR_CAT_PRIMARY)
#define MAP_CAT_LAUNCHER L(ARR_CAT_LAUNCHER)
#define MAP_CAT_HANDGUN L(ARR_CAT_HANDGUN)
#define MAP_CAT_UNIFORM_ITEMS L(ARR_CAT_UNIFORM_ITEMS)
#define MAP_CAT_VEST_ITEMS L(ARR_CAT_VEST_ITEMS)
#define MAP_CAT_BACKPACK_ITEMS L(ARR_CAT_BACKPACK_ITEMS)
#define MAP_CAT_ASSIGNED L(ARR_CAT_ASSIGNED)
#define MAP_CAT_INDENTITY L(ARR_CAT_INDENTITY)
#define MAP_CAT_TAGS L(ARR_CAT_TAGS)
#define MAP_CAT_SCRIPT L(ARR_CAT_SCRIPT)
#define MAP_CAT_UNIFORM_TEXTURES L(ARR_CAT_INDENTITY)