#define DBG_PREFIX "(dzn_gear) "
#define DBG_FUNC_PREFIX __FILE_SHORT__
#define DBG_FULL_PREFIX DBG_PREFIX + "[" + DBG_FUNC_PREFIX + "] "

// #define DEBUG true
#ifdef DEBUG
    #define DBG(MSG) diag_log format [DBG_FULL_PREFIX + MSG]
    #define DBG_1(MSG,ARG1) diag_log format [DBG_FULL_PREFIX + MSG, ARG1]
    #define DBG_2(MSG,ARG1,ARG2) diag_log format [DBG_FULL_PREFIX + MSG, ARG1,ARG2]
    #define DBG_3(MSG,ARG1,ARG2,ARG3) diag_log format [DBG_FULL_PREFIX + MSG, ARG1,ARG2,ARG3]
    #define DBG_4(MSG,ARG1,ARG2,ARG3,ARG4) diag_log format [DBG_FULL_PREFIX + MSG, ARG1,ARG2,ARG3,ARG4]
    #define DBG_5(MSG,ARG1,ARG2,ARG3,ARG4,ARG5) diag_log format [DBG_FULL_PREFIX + MSG, ARG1,ARG2,ARG3,ARG4,ARG5]
    #define DBG_6(MSG,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6) diag_log format [DBG_FULL_PREFIX + MSG, ARG1,ARG2,ARG3,ARG4,ARG5,ARG6]
    #define DBG_7(MSG,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7) diag_log format [DBG_FULL_PREFIX + MSG, ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7]
    #define DBG_8(MSG,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8) diag_log format [DBG_FULL_PREFIX + MSG, ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8]
    #define DBG_9(MSG,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8,ARG9) diag_log format [DBG_FULL_PREFIX + MSG, ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8,ARG9]
#else
    #define DBG(MSG)
    #define DBG_1(MSG,ARG1)
    #define DBG_2(MSG,ARG1,ARG2)
    #define DBG_3(MSG,ARG1,ARG2,ARG3)
    #define DBG_4(MSG,ARG1,ARG2,ARG3,ARG4)
    #define DBG_5(MSG,ARG1,ARG2,ARG3,ARG4,ARG5)
    #define DBG_6(MSG,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6)
    #define DBG_7(MSG,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7)
    #define DBG_8(MSG,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8)
    #define DBG_9(MSG,ARG1,ARG2,ARG3,ARG4,ARG5,ARG6,ARG7,ARG8,ARG9)
#endif

#define PREP(NAME) dzn_fnc_gear_##NAME = compileScript ['dzn_gear\fn\##NAME##.sqf']

#define L(X) toLowerANSI(X)

#include "categories.h"
