#include "defines.h"
/*
    Creates new kit with autogenerated name and adds it to kits pool.
    Most first unit or vehicle will be used.

    Params:
    0: _units (ARRAY) - units to pick from.
    1: _objects (ARRAY) - vics to pick from.

    Returns:
    _kitname (STRING) - name of the generated kit
*/
DBG_ "Params: %1", _this EOL;
params ["_units", "_objects"];

if (_this isEqualTo []) then {
    private _sel = (_self call [F(getSelected), []]);
    _units = (_sel # 0) + (_sel # 1);
    _objects = _sel # 2;
};

private _unitsCount = count _units;
private _objectsCount = count _objects;

// -- Only 1 unit or vehicle is selected
if (_unitsCount == 0 && _objectsCount == 0) exitWith {
    _self call [F(notify), [NOTIF_FAIL, NOTIF_MSG_NOT_SELECTED]];
    nil
};

if (
    (_unitsCount > 1 || _objectsCount > 1) ||
    (_unitsCount > 1 && _objectsCount > 0) ||
    (_unitsCount > 0 && _objectsCount > 1)
) exitWith {
    _self call [F(notify), [NOTIF_FAIL, NOTIF_MSG_TOO_MUCH_SELECTED]];
    nil
};

private _idx = 1 + (_self get Q(GenerationIndex));
_self set [Q(GenerationIndex), _idx];

if (_unitsCount > 0) exitWith {
    private _gear = ((_units # 0) call dzn_fnc_gear_getGear) call dzn_fnc_gear_make;
    private _kitname = toLower format [
        "kit_%1_%2__v%3",
        str(side (_units # 0)),
        [
            _gear get "PrimaryWeapon" get "class",
            _gear get "Launcher" get "class",
            _gear get "Handgun" get "class",
            _gear get "Uniform"
        ] select { _x != "" } select 0,
        _idx
    ];

    missionNamespace setVariable [_kitname, _gear, true];
    dzn_gear_personalKits pushBackUnique _kitname;

    _self call [F(notify), [NOTIF_OK, NOTIF_MSG_PERSONAL_GEAR_SAVED]];

    _kitname
};

private _gear = (_objects # 0) call dzn_fnc_gear_getCargoGear;
private _kitname = format [
    "cargo_kit_%1__v%2",
    typeOf (_objects # 0),
    _idx
];

missionNamespace setVariable [_kitname, _gear, true];
dzn_gear_cargoKits pushBackUnique _kitname;

_self call [F(notify), [NOTIF_OK, NOTIF_MSG_CARGO_GEAR_SAVED]];

_kitname